services:
  postgres_db:
    container_name: "postgres_ads_db"
    image: "postgres"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "ads-back"


